### ISSUE TITLE
定義ファイルを作成

### ISSUE THREAD

**Issue by yknk-stdy** [ishihama/lc-hubot#118]
lunch / nomuの共通でエリア/ジャンルを呼び出す用のファイルを作成

**Comment by nomotohiroki** [comment]
google spreadsheet を使うと、テーブル的に管理できて便利です。
tsv形式でシートを公開して、払い出されるurlにアクセスしてtsvを取ってきて、マスタとして扱ったり。
データ量が大きくなければ別段キャッシュ等も不要でしょう。

https://github.com/ishihama/lc-hubot/blob/master/scripts/lets_today_kanojo.coffee#L13-L18

この辺がそんなやり方をしています。

**Comment by yknk-stdy** [comment]
上のやり方でできました！
ありがとうございます〜〜
